# Generated by Django 5.0.6 on 2024-07-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lesson_requirements_video_what_you_learn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='name',
        ),
    ]
